# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Aux
tagline:          'A hardware project by Thomas Countz'
description:      'A microfeed of project updates.'
url:              'https://aux-blog.netlify.app'
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
repo:             https://github.com/thomascountz/aux
permalink:        feed/:name

twitter:
  username:       thomascountz
  card:           summary
  creator:        thomascountz
author:
  name:           'Thomas Countz'
  url:            https://thomascountz.com

paginate:         25
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
defaults:
  - scope:
      path: ""
    values:
      image: favicon.png
